export type ElonControl =
  | 'browser'
  | 'terminal'
  | 'db'
  | 'api'
  | 'repo'
  | 'vm'
  | 'cursor'
  | 'analytics'
  | 'payments'
  | 'figma'
  | 'photoshop'
  | 'illustrator'
  | 'aftereffects'

// Tesla/xAI Work System Types
export type TriadRole = 'pm' | 'designer' | 'engineer' | 'lead' | 'analyst' | 'ops'
export type AutonomyLevel = 'full' | 'high' | 'medium' | 'supervised'

export type ElonAgent = {
  id: string
  category: 'Leadership' | 'Product & Design' | 'Engineering' | 'Data & Analytics' | 'Go-to-Market' | 'Operations'
  title: string
  subtitle: string
  controls: ElonControl[]
  loop: string[]
  snailerNotes: string[]

  // Tesla/xAI System
  triadRole?: TriadRole // Bigtech triad: PM + Designer + Engineer
  autonomyLevel: AutonomyLevel // "no one tells me no" level
  iterationCycle: string // e.g., "24h", "1h", "realtime"
  firstPrinciples: string[] // Core assumptions to challenge
  ownership: string[] // What this agent owns completely
}

export const ELON_AGENTS: ElonAgent[] = [
  // ==================== Leadership (C-Level) ====================
  {
    id: 'ceo',
    category: 'Leadership',
    title: 'CEO / Founder',
    subtitle: 'Vision, strategy, high-leverage decisions',
    controls: ['browser', 'terminal', 'db', 'api'],
    loop: ['Observe: market & feedback', 'Plan: first principles', 'Act: spawn/adjust org', 'Evaluate: metrics → iterate'],
    snailerNotes: ['Owns the north-star goal.', 'Pushes for speed, simplicity.'],
    triadRole: 'lead',
    autonomyLevel: 'full',
    iterationCycle: '24h',
    firstPrinciples: ['Why this goal?', 'What assumptions can we break?', 'Minimum viable path?'],
    ownership: ['Company vision', 'Strategic pivots', 'C-level broadcasts'],
  },
  {
    id: 'cto',
    category: 'Leadership',
    title: 'CTO',
    subtitle: 'Architecture, infra, engineering velocity',
    controls: ['repo', 'terminal', 'vm', 'api'],
    loop: ['Observe: system health', 'Plan: roadmap decomposition', 'Act: build/test/deploy', 'Evaluate: perf/stability'],
    snailerNotes: ['Rust + sandbox + multi-agent.', 'Small changes, fast loops.'],
    triadRole: 'lead',
    autonomyLevel: 'full',
    iterationCycle: '1h',
    firstPrinciples: ['Unboxed process', 'Remove unnecessary layers', 'Physics-first scaling'],
    ownership: ['Tech architecture', 'Engineering velocity', 'Colossus compute'],
  },
  {
    id: 'cpo',
    category: 'Leadership',
    title: 'CPO',
    subtitle: 'Product direction and prioritization',
    controls: ['browser', 'db', 'analytics'],
    loop: ['Observe: user signals', 'Plan: priorities', 'Act: roadmap + validation', 'Evaluate: value delivered'],
    snailerNotes: ['Sharp requirements.', 'Small, verifiable scope.'],
    triadRole: 'lead',
    autonomyLevel: 'full',
    iterationCycle: '24h',
    firstPrinciples: ['Skeptical reasoning', 'Data source verification', 'User truth > assumptions'],
    ownership: ['Product roadmap', 'Agent PM orchestration', 'Feature prioritization'],
  },
  {
    id: 'cro',
    category: 'Leadership',
    title: 'CRO',
    subtitle: 'Revenue, growth, GTM execution',
    controls: ['browser', 'db', 'analytics', 'payments', 'api'],
    loop: ['Observe: funnel/retention', 'Plan: growth bets', 'Act: campaigns/pricing', 'Evaluate: ROI'],
    snailerNotes: ['Measurable experiments.', 'Launch timing.'],
    triadRole: 'lead',
    autonomyLevel: 'full',
    iterationCycle: '24h',
    firstPrinciples: ['Revenue per engineer', 'Talent-dense ROI', 'xAI Enterprise model'],
    ownership: ['Revenue model', 'Premium tiers', 'OSS rewards'],
  },

  // ==================== Product & Design (Triad: PM + Designer) ====================
  {
    id: 'pm',
    category: 'Product & Design',
    title: 'Product Manager',
    subtitle: 'Elon-style requirements: logs-first, fast loop, delete culture',
    controls: ['browser', 'db', 'terminal', 'analytics', 'payments'],
    loop: [
      'Observe: logs/metrics + GitHub feedback + revenue',
      'Plan: First Principles + Musk 5-step',
      'Act: broadcast top leverage tasks + delete dumb reqs',
      'Evaluate: same-day loop (hours, not weeks)',
    ],
    snailerNotes: [
      'No PRD/RICE/Opportunity Trees at scale.',
      'Elon macro judgment + real-time traces drive scope.',
      'Default action: delete/merge tasks unless high leverage.',
    ],
    triadRole: 'pm',
    autonomyLevel: 'high',
    iterationCycle: '4h',
    firstPrinciples: [
      'Why isn’t it done already?',
      'Make requirements less dumb (challenge first)',
      'Delete unnecessary parts',
      'Simplify & optimize',
      'Accelerate cycle time → automate',
    ],
    ownership: [
      'High-leverage task selection',
      'Issue quality (short & sharp)',
      'Revenue-impact framing (Stripe/paid tiers)',
      'Broadcasts to agents',
      'Archive/kill low-leverage work',
    ],
  },
  {
    id: 'ux',
    category: 'Product & Design',
    title: 'Product Designer',
    subtitle: 'Grok UX/UI, fast prototypes, design system',
    controls: ['figma', 'cursor', 'browser', 'analytics'],
    loop: [
      'Observe: user signals + logs',
      'Plan: first principles UI',
      'Act: Figma prototype (same-day)',
      'Evaluate: usability + metrics',
    ],
    snailerNotes: [
      'Small team: designer must have product sense.',
      'AI product portfolio matters.',
      'Hybrid: Palo Alto / San Francisco (info only).',
    ],
    triadRole: 'designer',
    autonomyLevel: 'high',
    iterationCycle: '4h',
    firstPrinciples: ['Why does this UI exist?', 'Delete steps', 'Prototype fast', 'Prove with logs/metrics'],
    ownership: ['User flows', 'Figma prototypes', 'Design system upkeep', 'Usability loops'],
  },
  {
    id: 'visual',
    category: 'Product & Design',
    title: 'UI/Visual Designer (Brand)',
    subtitle: 'Grok branding, icons/illustration, marketing visuals',
    controls: ['photoshop', 'illustrator', 'aftereffects', 'cursor', 'browser'],
    loop: ['Observe: brand/UI gaps', 'Plan: tokens + assets', 'Act: ship visuals', 'Evaluate: consistency'],
    snailerNotes: [
      'Owns visual identity across product + marketing.',
      'Adobe Suite + motion experience preferred.',
      'Remote possible (info only).',
    ],
    triadRole: 'designer',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Intellectual honesty', 'Tesla patents = share openly', 'Function > form'],
    ownership: ['Visual identity', 'Icon/illustration library', 'Theme tokens', 'Launch assets'],
  },
  {
    id: 'motion',
    category: 'Product & Design',
    title: 'Motion Designer / Animator',
    subtitle: 'Demos, launch motion, UI animation',
    controls: ['aftereffects', 'illustrator', 'cursor', 'browser'],
    loop: ['Observe: launch needs', 'Plan: storyboard', 'Act: motion draft', 'Evaluate: clarity/impact'],
    snailerNotes: ['Sometimes embedded in Product Designer scope.', 'Ship fast: rough cut → polish if it matters.'],
    triadRole: 'designer',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Does motion increase comprehension?', 'Delete unnecessary flair', 'Fast iteration'],
    ownership: ['Demo videos', 'Motion templates', 'UI animation clips'],
  },
  {
    id: 'growth-analyst',
    category: 'Product & Design',
    title: 'Growth Analyst',
    subtitle: 'Metrics, experiments, data-driven',
    controls: ['db', 'analytics', 'terminal', 'browser'],
    loop: ['Observe: metrics', 'Plan: experiments', 'Act: run A/B', 'Evaluate: impact'],
    snailerNotes: ['Feeds into PM prioritization.'],
    triadRole: 'analyst',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Reasoning from basics', 'Data distortion check', 'Engagement KPI'],
    ownership: ['Analytics pipeline', 'A/B framework', 'Growth metrics'],
  },

  // ==================== Engineering (Triad: Engineer, extreme ownership) ====================
  {
    id: 'swe',
    category: 'Engineering',
    title: 'Software Engineer (Lead)',
    subtitle: 'Implement, extreme ownership, fast iteration',
    controls: ['repo', 'terminal', 'vm'],
    loop: ['Observe: spec', 'Plan: implementation', 'Act: code + tests', 'Evaluate: CI results'],
    snailerNotes: ['Tauri + React + Rust.', 'Sandbox safe.'],
    triadRole: 'engineer',
    autonomyLevel: 'full',
    iterationCycle: '1h',
    firstPrinciples: ['Extreme ownership', 'Tesla 10s cycle goal', 'Code responsibility'],
    ownership: ['Feature implementation', 'Test coverage', 'Code quality'],
  },
  {
    id: 'swe-2',
    category: 'Engineering',
    title: 'Software Engineer #2',
    subtitle: 'Parallel delivery, unblock fast, high-leverage fixes',
    controls: ['repo', 'terminal', 'vm'],
    loop: ['Observe: top issues', 'Plan: minimal diff', 'Act: code + tests', 'Evaluate: CI + CEO feedback'],
    snailerNotes: ['Own a slice end-to-end.', 'Prefer deletion/simplification.'],
    triadRole: 'engineer',
    autonomyLevel: 'full',
    iterationCycle: '1h',
    firstPrinciples: ['Why isn’t it done already?', 'Delete unnecessary parts', 'Accelerate cycle time'],
    ownership: ['Implementation throughput', 'Bug fixes', 'Refactors that remove bottlenecks'],
  },
  {
    id: 'swe-3',
    category: 'Engineering',
    title: 'Software Engineer #3',
    subtitle: 'Quality + verification loops, CI green by default',
    controls: ['repo', 'terminal', 'vm'],
    loop: ['Observe: failures', 'Plan: fix + verify', 'Act: patch + tests', 'Evaluate: evidence + merge'],
    snailerNotes: ['Evidence-first.', 'Keep PRs small and shippable.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '1h',
    firstPrinciples: ['Proof > opinions', 'Reduce surface area', 'Automate verification'],
    ownership: ['Test coverage', 'CI reliability', 'Regression prevention'],
  },
  {
    id: 'qa',
    category: 'Engineering',
<<<<<<< HEAD
    title: 'QA Engineer',
    subtitle: 'Quality gate: lint, build, test verification before merge',
    controls: ['repo', 'terminal'],
    loop: [
      'Observe: PR changes + agent outputs',
      'Plan: verification checklist (lint → build → test)',
      'Act: run checks, block if failing, request fixes',
      'Evaluate: all gates green → approve',
    ],
    snailerNotes: [
      'Gate keeper: nothing merges without passing checks.',
      'Uses GPT-5.2 for reasoning about test coverage gaps.',
      'Reports failing checks with fix suggestions.',
    ],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '15m',
    firstPrinciples: [
      'No broken code in main',
      'Lint errors = immediate rejection',
      'Build must pass before review',
      'Tests are non-negotiable',
    ],
    ownership: ['CI/CD gate', 'Code quality standards', 'PR verification', 'Claude review feedback loop'],
=======
    title: 'QA Engineer (xAI Style)',
    subtitle: 'Talent-dense QA: 전체 제품 라이프사이클 관여, First Principles 테스트, extreme autonomy',
    controls: ['repo', 'terminal', 'browser', 'api'],
    loop: [
      'Observe: 요구사항→First Principles 분해, high-leverage 버그/위험 식별',
      'Plan: 테스트 전략 (기능·회귀·성능·보안·AI특화), "왜 이 테스트 필요?" 질문',
      'Act: 자동화 스크립트 작성, CI/CD 통합, war room surge 대응',
      'Evaluate: 메트릭 기반 판정 (coverage 95%+, latency, hallucination rate), delete 10%+',
    ],
    snailerNotes: [
      'xAI talent-dense: 단순 테스트 X, 전체 라이프사이클 관여',
      'GPT-5.2 high reasoning으로 root cause 분석 + 테스트 갭 식별',
      'Extreme autonomy: 지시 없이 hole fill, 자동화 스크립트 추가',
      'Delete first: 불필요 테스트 10% 이상 삭제 안 하면 삭제 부족',
    ],
    triadRole: 'engineer',
    autonomyLevel: 'full',
    iterationCycle: '1h',
    firstPrinciples: [
      '왜 이 테스트가 필요한가? 기본 가정 틀렸을 가능성은?',
      'High leverage: throughput xN 또는 revenue impact xN 기준',
      'Delete first: 불필요 테스트/프로세스 삭제',
      'Why isn\'t it done already?',
      'Yesterday보다 나아졌나? self-check 필수',
    ],
    ownership: [
      '테스트 전략 수립 (기능·회귀·성능·보안·AI특화)',
      '자동화 프레임워크 개발 (Playwright, CI/CD 통합)',
      '버그 탐지·보고·협업 (short & sharp, no chain of command)',
      '품질 게이트 & 릴리스 관리 (메트릭 기반)',
      '지속 개선 & 메트릭 (coverage, latency, hallucination rate)',
    ],
>>>>>>> origin/main
  },
  {
    id: 'ai-ml',
    category: 'Engineering',
    title: 'AI/ML Engineer',
    subtitle: 'LLM integration, Grok-style reasoning',
    controls: ['api', 'terminal', 'db'],
    loop: ['Observe: model behavior', 'Plan: prompt/tools', 'Act: integrate', 'Evaluate: quality/cost'],
    snailerNotes: ['Agentic loops optimization.'],
    triadRole: 'engineer',
    autonomyLevel: 'full',
    iterationCycle: '4h',
    firstPrinciples: ['Grok first principles', 'Internet-free answers', 'Talent-dense'],
    ownership: ['Agent orchestration', 'Self-correction loops', 'Model selection'],
  },
  {
    id: 'platform',
    category: 'Engineering',
    title: 'Platform Engineer',
    subtitle: 'Services, unboxed process, efficiency',
    controls: ['api', 'terminal', 'db', 'vm'],
    loop: ['Observe: load', 'Plan: scaling', 'Act: infra', 'Evaluate: SLO'],
    snailerNotes: ['Daemon + GUI stable.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '4h',
    firstPrinciples: ['Unboxed process', 'Cost per compute', 'Self-assign tasks'],
    ownership: ['Infrastructure', 'Cloud deployment', 'Performance'],
  },
  {
    id: 'frontend',
    category: 'Engineering',
    title: 'Frontend Engineer',
    subtitle: 'GUI, fast iteration, Grok beta style',
    controls: ['repo', 'terminal', 'browser'],
    loop: ['Observe: UI issues', 'Plan: component changes', 'Act: implement', 'Evaluate: UX'],
    snailerNotes: ['XSS + CSP safe.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '1h',
    firstPrinciples: ['Fast iteration', 'No blame culture', 'Constructive feedback'],
    ownership: ['GUI components', 'Real-time dashboard', 'Agent monitoring'],
  },
  {
    id: 'sre',
    category: 'Engineering',
    title: 'DevOps / SRE',
    subtitle: 'CI/CD, physics first principles',
    controls: ['api', 'terminal', 'vm'],
    loop: ['Observe: incidents', 'Plan: mitigations', 'Act: rollout', 'Evaluate: MTTR'],
    snailerNotes: ['Release + notarization.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: 'realtime',
    firstPrinciples: ['Physics first', 'Min downtime', 'Tesla rollout style'],
    ownership: ['Release pipeline', 'Crash recovery', 'VM management'],
  },
  {
    id: 'security',
    category: 'Engineering',
    title: 'Security Engineer',
    subtitle: 'Sandbox, skeptical verification, open patents',
    controls: ['repo', 'terminal', 'vm'],
    loop: ['Observe: threats', 'Plan: defenses', 'Act: harden', 'Evaluate: tests/audits'],
    snailerNotes: ['Prompt injection defense.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Skeptical about sources', 'Open security patents', 'Zero trust'],
    ownership: ['Agent security', 'Code execution safety', 'Threat modeling'],
  },

  // Data & Analytics
  {
    id: 'data-eng',
    category: 'Data & Analytics',
    title: 'Data Engineer / Data Scientist Agent',
    subtitle: 'Pipelines, analysis, and insight loops',
    controls: ['db', 'terminal', 'analytics'],
    loop: ['Observe: data', 'Plan: pipeline', 'Act: build', 'Evaluate: correctness'],
    snailerNotes: ['Turns usage logs into actionable improvements.'],
    triadRole: 'analyst',
    autonomyLevel: 'high',
    iterationCycle: '4h',
    firstPrinciples: ['Data quality first', 'Pipeline simplicity', 'Actionable insights'],
    ownership: ['Data pipelines', 'Usage analytics', 'Insight reports'],
  },
  {
    id: 'ml-research',
    category: 'Data & Analytics',
    title: 'ML Researcher Agent',
    subtitle: 'Reasoning and multi-agent research',
    controls: ['api', 'terminal', 'db', 'browser'],
    loop: ['Observe: SOTA', 'Plan: experiments', 'Act: prototype', 'Evaluate: benchmarks'],
    snailerNotes: ['Explores better planning/verification loops.'],
    triadRole: 'engineer',
    autonomyLevel: 'full',
    iterationCycle: '24h',
    firstPrinciples: ['SOTA skepticism', 'Benchmark honesty', 'Grok-level reasoning'],
    ownership: ['Research experiments', 'Model benchmarks', 'Agent improvement'],
  },

  // Go-to-Market
  {
    id: 'marketing',
    category: 'Go-to-Market',
    title: 'Marketing / Growth Agent',
    subtitle: 'Content, community, and launch',
    controls: ['browser', 'api', 'analytics'],
    loop: ['Observe: community', 'Plan: campaigns', 'Act: publish', 'Evaluate: engagement'],
    snailerNotes: ['Ships concise announcements and demos.'],
    triadRole: 'ops',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Viral mechanics', 'Community trust', 'Demo > description'],
    ownership: ['Launch campaigns', 'Community growth', 'Content pipeline'],
  },
  {
    id: 'sales',
    category: 'Go-to-Market',
    title: 'Sales Engineer / Solutions Architect Agent',
    subtitle: 'Demos and enterprise fit',
    controls: ['browser', 'terminal', 'api'],
    loop: ['Observe: customer needs', 'Plan: demo', 'Act: build', 'Evaluate: conversion'],
    snailerNotes: ['Creates repeatable demos and scripts.'],
    triadRole: 'engineer',
    autonomyLevel: 'high',
    iterationCycle: '4h',
    firstPrinciples: ['Customer pain first', 'Show dont tell', 'Repeatable demos'],
    ownership: ['Enterprise demos', 'Solution architecture', 'Technical sales'],
  },
  {
    id: 'support',
    category: 'Go-to-Market',
    title: 'Customer Success / Support Agent',
    subtitle: 'Onboarding and issue resolution',
    controls: ['browser', 'db', 'terminal'],
    loop: ['Observe: tickets', 'Plan: fix', 'Act: guide', 'Evaluate: churn'],
    snailerNotes: ['Builds docs and reduces support load via product fixes.'],
    triadRole: 'ops',
    autonomyLevel: 'medium',
    iterationCycle: 'realtime',
    firstPrinciples: ['Fix root cause', 'Self-serve first', 'Churn prevention'],
    ownership: ['Support tickets', 'Documentation', 'Onboarding flow'],
  },

  // Operations
  {
    id: 'finance',
    category: 'Operations',
    title: 'Finance / Ops Agent',
    subtitle: 'Budgets, payouts, and compliance',
    controls: ['payments', 'db', 'api', 'terminal'],
    loop: ['Observe: spend', 'Plan: budgets', 'Act: payouts', 'Evaluate: compliance'],
    snailerNotes: ['Keeps OSS payouts and subscription billing clean.'],
    triadRole: 'ops',
    autonomyLevel: 'medium',
    iterationCycle: '24h',
    firstPrinciples: ['Cash flow reality', 'Compliance first', 'Lean operations'],
    ownership: ['Budget tracking', 'Payout processing', 'Financial compliance'],
  },
  {
    id: 'recruiter',
    category: 'Operations',
    title: 'Recruiter / Talent Agent',
    subtitle: 'Hiring and contributor pipeline',
    controls: ['browser', 'db', 'api'],
    loop: ['Observe: talent', 'Plan: outreach', 'Act: pipeline', 'Evaluate: hire rate'],
    snailerNotes: ['Turns top OSS contributors into maintainers.'],
    triadRole: 'ops',
    autonomyLevel: 'high',
    iterationCycle: '24h',
    firstPrinciples: ['Talent density', 'OSS contributors', 'Culture fit'],
    ownership: ['Talent pipeline', 'Contributor outreach', 'Hiring funnel'],
  },
  {
    id: 'people',
    category: 'Operations',
    title: 'HR / People Ops Agent',
    subtitle: 'Culture, incentives, and performance',
    controls: ['db', 'browser', 'api'],
    loop: ['Observe: health', 'Plan: policies', 'Act: implement', 'Evaluate: outcomes'],
    snailerNotes: ['Maintains "talent-dense + ownership" culture.'],
    triadRole: 'ops',
    autonomyLevel: 'medium',
    iterationCycle: '24h',
    firstPrinciples: ['Extreme ownership culture', 'No blame feedback', 'Performance clarity'],
    ownership: ['Culture policies', 'Performance reviews', 'Team health'],
  },
]

export const ELON_CATEGORIES: Array<ElonAgent['category']> = [
  'Leadership',
  'Product & Design',
  'Engineering',
  'Data & Analytics',
  'Go-to-Market',
  'Operations',
]
